#!/bin/bash
usage() {
echo 'usage: ROOT=/path/to/root PACKAGES="apt packages" aptstrap [options] 
options:
init - prepare for aptstrapping
bootstrap - bootstrap the root (without initializing
initstrap - initialize and bootstrap (default)
clean - clean up apt archives (run apt clean in the root)

Note: aptstrap requires apt installed on your system.'
}
init() {
mkdir -p $ROOT/usr/bin $ROOT/usr/lib $ROOT/var/lib $ROOT/etc $ROOT/var/log $ROOT/boot $ROOT/usr/lib64 $ROOT/usr/include
ln -s $ROOT/usr/bin $ROOT/bin
ln -s $ROOT/usr/lib $ROOT/lib
ln -s $ROOT/usr/lib64 $ROOT/lib64
cp $(which apt) $ROOT/usr/bin/apt > /dev/null 2>&1
}
